version: "3.7"

services:
    react-node:
        build:
            args:
                - NODE_VER=current-slim
            context: .
            dockerfile: Dockerfile
        tty: true
        command: sh -c 'yarn && yarn tcm & yarn log & yarn dev --host'
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./:/home/node/street
        ports:
            - "5173:5173"
